Separate packages.
Flexberry/NewPlatform.Flexberry.AuditBigData pull request #14
Opened 2021-06-05 13:51 UTC by NicholasNoise

2021-06-06 07:23 UTC, bratchikov requested changes

2021-06-06 07:23 UTC, bratchikov commented on Directory.Build.targets
> +    <!--<AdditionalFiles Include="$(MSBuildThisFileDirectory)\Flexberry.ruleset" />-->
Это надо раскомментировать или удалить. Ниже тоже.

2021-06-06 07:23 UTC, bratchikov commented on Objects/NewPlatform.Flexberry.AuditBigData.Objects.csproj
> +    <PackageId>NewPlatform.Flexberry.AuditBigData.Objects</PackageId>
Зачем это выносить в отдельный пакет?

2021-06-06 07:23 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData.Abstractions/NewPlatform.Flexberry.AuditBigData.Abstractions.csproj
> +    <PackageId>NewPlatform.Flexberry.AuditBigData.Abstractions</PackageId>
Как-то сразу очень много пакетов стало. Пока не видится ситуации, что кому-то может понадобиться этот пакет сам по себе.

2021-06-06 07:23 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData.Serialization.Json/NewPlatform.Flexberry.AuditBigData.Serialization.Json.csproj
> +    <PackageId>NewPlatform.Flexberry.AuditBigData.Serialization.Json</PackageId>
Это основная и базовая реализация сериализатора. Вполне нормально воспринимается, если она будет жить в основном пакете.

2021-06-06 07:23 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData.nuspec
> -﻿<?xml version="1.0" encoding="utf-8"?>
У нас nuspec остаётся основным способом описания пакетов для всех проектов в технологии, поэтому для единообразия я предлагаю продолжить его использование. Искать нужные параметров пакетов по csproj-файлам - то ещё удовольствие. С точки зрения понимания структуры исходного кода nuspec более дружественен разработчикам, особенно, новичкам или тем, кто плохо запоминает детали каждого из 100+ проектов.

2021-06-06 09:20 UTC, NicholasNoise commented on NewPlatform.Flexberry.AuditBigData.Abstractions/NewPlatform.Flexberry.AuditBigData.Abstractions.csproj
> +    <PackageId>NewPlatform.Flexberry.AuditBigData.Abstractions</PackageId>
Чистая архитектура, абстракции определяются отдельно от реализаций

2021-06-06 09:21 UTC, NicholasNoise commented on NewPlatform.Flexberry.AuditBigData.Serialization.Json/NewPlatform.Flexberry.AuditBigData.Serialization.Json.csproj
> +    <PackageId>NewPlatform.Flexberry.AuditBigData.Serialization.Json</PackageId>
Может быть заменена на реализацию через `System.Json`; так же имеет зависимость, которая требуется только для сериализации.

2021-06-06 09:23 UTC, NicholasNoise commented on Objects/NewPlatform.Flexberry.AuditBigData.Objects.csproj
> +    <PackageId>NewPlatform.Flexberry.AuditBigData.Objects</PackageId>
Модель хранения данных отдельно, т.к. может быть использована для чтения независимо от аудита

2021-06-06 09:31 UTC, NicholasNoise commented on NewPlatform.Flexberry.AuditBigData.Serialization.Json/NewPlatform.Flexberry.AuditBigData.Serialization.Json.csproj
> +    <PackageId>NewPlatform.Flexberry.AuditBigData.Serialization.Json</PackageId>
"основная и базовая" - не является причиной для группировки в монолит

2021-06-06 09:33 UTC, NicholasNoise commented on NewPlatform.Flexberry.AuditBigData.nuspec
> -﻿<?xml version="1.0" encoding="utf-8"?>
Формат `nuspec` наоборот крайне не дружественен: требует дублирования настроек, в т.ч. зависимостей, упаковки файлов и прочего. Если исходить из общепринятого принципа "один проект = один пакет", то описаной проблемы не возникает, т.к. всегда знаешь, где искать "параметры", а использованные мною ` Directory.Build.*`-файлы упрощают и стандартизируют настройку пакетирования и сборки.

2021-06-07 08:00 UTC, mao29 commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
А разве нет правила именования приватных полей через _camelCase, чтобы потом в методах с локальными переменными не путать? Мне казалось в технологии это тоже было

2021-06-07 08:00 UTC, mao29 commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditConverterHelper.cs
> +        private const string CustomOperation = "CustomOperation";
```suggestion
        private readonly string CustomOperation = "CustomOperation";
```

2021-06-07 08:04 UTC, mao29 commented on NewPlatform.Flexberry.AuditBigData.nuspec
> -﻿<?xml version="1.0" encoding="utf-8"?>
А что за правило один проект=один пакет? Мне кажется могут быть проекты, которые сами по себе в пакет не упаковываются, а просто project reference-ами добавлены в главный проект. Но я так понимаю упаковщик разруливает такие ситуации и собирает в пакет основного проекта также сборки проектов по project reference-ам?

2021-06-07 08:07 UTC, mao29 commented on NewPlatform.Flexberry.AuditBigData.Abstractions/NewPlatform.Flexberry.AuditBigData.Abstractions.csproj
> +    <PackageId>NewPlatform.Flexberry.AuditBigData.Abstractions</PackageId>
Захочет кто-нибудь не в json, а в protobuf запаковать аудит и сразу понадобится

2021-06-07 09:11 UTC, NicholasNoise commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditConverterHelper.cs
> +        private const string CustomOperation = "CustomOperation";
Почему `readonly`? В чем преимущество над `const`?

2021-06-07 09:14 UTC, NicholasNoise commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
SA1309 и SA1310

2021-06-07 09:22 UTC, NicholasNoise commented on NewPlatform.Flexberry.AuditBigData.nuspec
> -﻿<?xml version="1.0" encoding="utf-8"?>
Да, _можно_ упаковывать несколько проектов\библиотек в один пакет, но MS **рекомендует** паковать по одной сборке в пакет: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#decide-which-assemblies-to-package

2021-06-07 09:22 UTC, NicholasNoise commented on NewPlatform.Flexberry.AuditBigData.Abstractions/NewPlatform.Flexberry.AuditBigData.Abstractions.csproj
> +    <PackageId>NewPlatform.Flexberry.AuditBigData.Abstractions</PackageId>
... или в xml

2021-06-07 10:05 UTC, mao29 commented on NewPlatform.Flexberry.AuditBigData.nuspec
> -﻿<?xml version="1.0" encoding="utf-8"?>
Тем не менее они при этом сами формируют мета-пакеты, которые при установке притягивают сразу пачку пакетов. Этак нам ОРМ придется на сколько пакетов разбить? Я не против увеличить количество пакетов, но против подхода один проект-один пакет. Либо нужны мета-пакеты тогда.

2021-06-07 10:06 UTC, mao29 commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
Я осуждаю это правило по озвученным в исходным комментарии соображениям. Прошу рассмотреть возможность его изменения

2021-06-07 10:08 UTC, mao29 commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditConverterHelper.cs
> +        private const string CustomOperation = "CustomOperation";
Хм. В случае private ни в чем. Был бы public, могла бы быть ситуация, когда зависимые сборки необходимо было бы перекомпилировать, если в этой сборке поменяется значение константы. 
Можешь отклонить предложение

2021-06-07 12:15 UTC, kuzkok commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
> 
> 
> А разве нет правила именования приватных полей через _camelCase, чтобы потом в методах с локальными переменными не путать? Мне казалось в технологии это тоже было

Такое именование изначально в эмбер было, а вот в .net никогда не видел - там всегда private camelCase, если что-то должно быть public - то CamelCase {get ;set;}

2021-06-07 12:49 UTC, mao29 commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
В js у такого наименования несколько иные цели, там нет приватных и публичных методов. Зачем так делать в C# я выше написал. Если мы не требуем _camlCase, то должны требовать всегда использовать `this` для приватных полей. Иначе читаемость кода падает - приходится думать это внутреннее поле класса используется или локальная переменная.

2021-06-07 13:20 UTC, NicholasNoise commented on NewPlatform.Flexberry.AuditBigData.nuspec
> -﻿<?xml version="1.0" encoding="utf-8"?>
Мета-пакеты, не содержащие в себе сборок, аналогичные [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/), [Unity](https://www.nuget.org/packages/Unity/) или [App.Metrics](https://www.nuget.org/packages/App.Metrics), вполне имеют право на существование, т.к. объективно облегчают первый старт при использовании какой-либо технологии.

В любом случае не вижу аргументов против `один проект-один пакет`, применимо к данному репозиторию и нашему случаю:
- `Objects` может использоваться для операций чтения\выборок
- `Serialization.Json` может быть заменен на xml или protobuf
- `Abstractions` появляются как "требование" чистой архитектуры для корректной поддержки переопределения (как минимум) сериализации

2021-06-07 13:25 UTC, NicholasNoise commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
Для того, чтобы не было путаницы между полями и переменными, придумали `this`.

2021-06-07 14:42 UTC, mao29 commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
Если мне не изменяет память, решение с _ еще в стайлгайде политеха изначальном было. `this` не для этого придумали и мне кажется использование повсеместно `this.` перед всеми приватными полями читаемость кода ухудшит сильнее, чем _. А на тему SA1401 я не знаю чем руководствуются авторы этого правила, но озвученную изначально проблему оно не решает, а как раз создает, и оно не высечено в камне, потому и предлагаю его заменить на разумную альтернативу. Я у себя в студии даже стандартные сниппеты генерации полей в классе переделал, чтобы сразу генерилось наименование в формате `_fieldTypeName`. Если все прямо так против такого соглашения, ну давайте идти до конца, тогда прошу повсеместно поиспользовать `this.` в коде, где используются свойства класса.

2021-06-07 15:19 UTC, archaim commented on NewPlatform.Flexberry.AuditBigData.nuspec
> -﻿<?xml version="1.0" encoding="utf-8"?>
Поддерживаю @NicholasNoise в стремлении придерживаться принципа `1 проект - один пакет` где это возможно. Принцип здесь такой: если есть возможность, что проект будет включён в несколько пакетов, он должен сам быть пакетом.
Nuspec тоже лучше избегать где возможно.

2021-06-07 15:49 UTC, archaim commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
Есть причина почему this лучше. Когда я пишу `_` IntelliSence показывает приватные поля, а также все внешние классы, неймспейсы, сниппеты и ещё какую-то хрень. Когда я набираю `this.`, я вижу только члены текущего класса.

2021-06-07 16:25 UTC, mao29 commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
Никаких внешних классов, неймспейсов и сниппетов, начинающихся с `_` быть не должно. Эта конвенция исключительно для private и protected членов класса. Ни для чего больше ее нельзя использовать. Кстати вот отголоски истории, откуда это все пошло: https://stackoverflow.com/questions/9782084/naming-conventions-in-c-sharp-underscores
И хотя действительно пишут, что сейчас `_` это типа моветон, но тоже в комментах есть мнение, что `this.` это страдания и по факту мало кто этому следует.

2021-06-07 16:29 UTC, mao29 commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
Хм. А еще и в официальных доках есть прямая рекомендация: https://docs.microsoft.com/ru-ru/dotnet/csharp/fundamentals/coding-style/coding-conventions#camel-case
Хотя там еще какие-то новые для меня истории насчет статических и потокобезопасных полей...

2021-06-07 18:59 UTC, NicholasNoise commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
SX1309 - полная противоположность SA1309, ибо принуждает использовать `_` в начале приватных полей.

2021-06-10 05:12 UTC, archaim commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
> Никаких внешних классов, неймспейсов и сниппетов, начинающихся с `_` быть не должно.
Их и нет. Отображаются вообще все. Просто открой студию и попробуй.

2021-06-10 06:42 UTC, mao29 commented on NewPlatform.Flexberry.AuditBigData/LegacyAuditManager.cs
> +        private readonly ILegacyAuditConverter auditConverter;
Да, понятно. Надо только учитывать, что большую часть времени код не пишется, а читается. При чтении IntelliSense не особо задействован.

2021-07-30 09:16 UTC, AntonIV8 approved these changes

2021-07-30 09:20 UTC, merged