Initial implementation.
Flexberry/NewPlatform.Flexberry.AuditBigData pull request #2
Opened 2020-12-23 03:41 UTC by leoleopon

2021-02-04 17:45 UTC, bratchikov requested changes

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +                        auditSerializer.Serialize(auditAdditionalInfo),
Лучше не использовать такие "матрёшечные" вызовы методов. Результат работы сериализатора хорошо бы записать в переменную и проверить, что он нас устраивает (может быть null?).

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +                    TypeOfAuditOperation2AuditOperationType(commonAuditParameters.TypeOfAuditOperation).ToString(),
Тут тоже лучше вынести в переменную и если требуется проверить результат.

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +                    auditSerializer.Serialize(commonAuditParameters),
Тоже вынести в переменную.

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +                    CustomOperation2BigDataCustomOperation(checkedCustomAuditParameters.CustomOperation),
Вынести в переменную.

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +                    auditSerializer.Serialize(checkedCustomAuditParameters.CustomAuditFieldList),
Вынести в переменную.

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +            primaryAuditRecord.SetExistObjectPrimaryKey(headAuditEntityPrimaryKey);
Проверь, что headAuditEntityPrimaryKey не null.

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +        protected virtual AuditRecord CreateRatifyingAuditRecord(
Зачем этот метод, если он просто перевызывает другой?

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/IAuditSerializer.cs
> +    public interface IAuditSerializer
Так выходит, что этот интерфейс завязан на старые интерфейсы аудита. Это даёт нам выигрыш в том, что внедрение в проекты выполняется легче, но и дальше тащит за собой имеющиеся проблемы старых интерфейсов. Может быть этот интерфейс назвать IAuditSerializerLegacy? Для будущего развития будет другой интерфейс IAuditSerializer, в котором будем оперировать только DataObject и представлениями, как я и предполагал изначально?

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/DefaultAuditSerializer.cs
> +        {
Надо проверить value на IsNullOrEmpty.

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/DefaultAuditSerializer.cs
> +            View auditView = Information.GetView(commonAuditParameters.AuditView, operatedObject.GetType());
operatedObject.GetType() вынести в переменную. Ниже она снова понадобится.

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/DefaultAuditSerializer.cs
> +            var detailObjectOldArray = oldDetailArray.GetAllObjects();
Если по правой части нельзя понять что это за тип возвращается, как тут - var не используем. Ниже тоже есть эти проблемы.

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/DefaultAuditSerializer.cs
> +        private class FieldAuditData : IFieldAuditData
Лучше вынеси в отдельный файл.

2021-02-04 17:45 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/DefaultAuditSerializer.cs
> +            public string Field { private get; set; }
Добавь всем свойствам XML-комментарии, квалификаторы доступа.

2021-02-04 17:45 UTC, bratchikov commented on Tests/NewPlatform.Flexberry.AuditBigData.Tests/SqlScripts/MSSql.create.sql
> +	 [UserName] VARCHAR(255)  NULL,
Надо в маппинге сделать nvarchar(1024) хотя бы. Для login и objectType тоже.

2021-02-04 17:45 UTC, bratchikov commented on Tests/NewPlatform.Flexberry.AuditBigData.Tests/SqlScripts/MSSql.create.sql
> +	 [ObjectPrimaryKey] LONGVARBINARY  NULL,
Какой интересный тип. Это корректно?

2021-02-04 17:48 UTC, bratchikov commented
А что с тестами? Билд как-то интересно падает.

2021-03-17 13:41 UTC, leoleopon commented on Tests/NewPlatform.Flexberry.AuditBigData.Tests/SqlScripts/MSSql.create.sql
> +	 [ObjectPrimaryKey] LONGVARBINARY  NULL,
Тип исправлен на NVARCHAR(38), как в оригинальном проекте.

2021-03-17 21:49 UTC, leoleopon commented on Tests/NewPlatform.Flexberry.AuditBigData.Tests/SqlScripts/MSSql.create.sql
> +	 [UserName] VARCHAR(255)  NULL,
Исправил.

2021-03-17 21:57 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +        protected virtual AuditRecord CreateRatifyingAuditRecord(
Это сделано для унификации вызовов.

2021-03-17 22:08 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +                        auditSerializer.Serialize(auditAdditionalInfo),
Проверка не требуется. Аргументы вынес в переменные.

2021-03-17 22:09 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +                    TypeOfAuditOperation2AuditOperationType(commonAuditParameters.TypeOfAuditOperation).ToString(),
Проверка не требуется. Аргументы вынес в переменные.

2021-03-17 22:11 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +                    auditSerializer.Serialize(commonAuditParameters),
Проверка не требуется. Аргументы вынес в переменные.

2021-03-17 22:12 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +                    CustomOperation2BigDataCustomOperation(checkedCustomAuditParameters.CustomOperation),
Проверка не требуется. Аргументы вынес в переменные.

2021-03-17 22:13 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +                    CustomOperation2BigDataCustomOperation(checkedCustomAuditParameters.CustomOperation),
Проверка не требуется. Аргументы вынес в переменные.

2021-03-17 22:15 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +                    auditSerializer.Serialize(checkedCustomAuditParameters.CustomAuditFieldList),
Проверка не требуется. Аргументы вынес в переменные.

2021-03-17 23:01 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/DefaultAuditSerializer.cs
> +            public string Field { private get; set; }
Квалификаторы доступа для членов класса, явно реализующих интерфейс, недопустимы. Добавил XML-комментарии.

2021-03-17 23:25 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/DefaultAuditSerializer.cs
> +            View auditView = Information.GetView(commonAuditParameters.AuditView, operatedObject.GetType());
Унаследованный код. Исправил.

2021-03-17 23:30 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/DefaultAuditSerializer.cs
> +        {
Значения null и string.Empty параметра value обрабатываются кодом реализации.

2021-03-17 23:33 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/DefaultAuditSerializer.cs
> +        private class FieldAuditData : IFieldAuditData
Это private класс, используемый в реализации данного сериализатора.

2021-03-17 23:48 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/DefaultAuditSerializer.cs
> +            var detailObjectOldArray = oldDetailArray.GetAllObjects();
Унаследованный код. Исправил.

2021-03-17 23:57 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/IAuditSerializer.cs
> +    public interface IAuditSerializer
Переименовал интерфейс IAuditSerializer в ILegacyAuditSerializer,  переименовал класс реализации DefaultAuditSerializer указанного интерфейса в LegacyAuditSerializer.

2021-03-18 00:40 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/AuditManager.cs
> +            primaryAuditRecord.SetExistObjectPrimaryKey(headAuditEntityPrimaryKey);
Поправил.

2021-03-18 08:55 UTC, bratchikov approved these changes

2021-03-19 06:44 UTC, bratchikov approved these changes

2021-03-19 06:44 UTC, bratchikov commented on NewPlatform.Flexberry.AuditBigData/NewPlatform.Flexberry.AuditBigData.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
Проверить, что в nuspec указана именно эта зависимость

2021-03-19 06:44 UTC, bratchikov commented on Tests/NewPlatform.Flexberry.AuditBigData.Tests/BaseIntegratedTest.cs
> +                if (!(tempDbNamePrefix.Length <= 12)) // Max length is 63 (-18 -32).
Эти ограничения лишние, наверное. Завести задачу на удаление этого ограничения.

2021-03-19 09:20 UTC, leoleopon commented on NewPlatform.Flexberry.AuditBigData/NewPlatform.Flexberry.AuditBigData.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
Поправил.

2021-03-19 09:31 UTC, merged